### ISSUE TITLE
web_demo in docker container is not working

### ISSUE THREAD

**Issue by flashspys** [cyang-kth/osm_mapmatching#11]
After successfully building the docker container and running installing tornado and flask in it, I ran into the following error:

```bash
$ root:/fmm/example/web_demo# python2 web_demo.py 
Traceback (most recent call last):
  File "web_demo.py", line 7, in <module>
    import tornado.wsgi
  File "/usr/local/lib/python2.7/dist-packages/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
                     ^
SyntaxError: invalid syntax

```
Is there any specific version of tornado that I've to install?

**Comment by cyang-kth** [comment]
@flashspys 
If I check the link here
https://github.com/cyang-kth/fmm/tree/master/example/web_demo

Did you supply a json file to define the configurations?

```
python web_demo.py -c stmatch_config.json
```

For `fmm`, you need to precompute an UBODT from the shapefile first.

**Comment by flashspys** [comment]
I don't think that this will help with a syntax error in tornado.

**Comment by flashspys** [comment]
This issue should not be in this repo but in the https://github.com/cyang-kth/fmm repo.

**Comment by cyang-kth** [comment]
The same problem is mentioned here 
https://github.com/janeczku/calibre-web/issues/1070

**Comment by flashspys** [comment]
So, the web_demo is not usable anymore?

**Comment by cyang-kth** [comment]
I have tornado version of 5.0.1, which version are you using? Maybe you need to revert to an old version?
