### ISSUE TITLE
Downloading data for large region

### ISSUE THREAD

**Issue by Vedanta-Z** [cyang-kth/osm_mapmatching#15]
Hi,
I am trying to download for an extremely large region.

Would be great if you have some tips .

I am getting memory error even after allocating a server with >300GB memory.
I tried to use osmnx 1.0.1 , But the code snippet you shared does not work with it.(Getting fiona errors)

Need to have all highways, So filtering does not seem to be an option as well.

Would using a function like [graph_from_xml](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.graph.graph_from_xml) work?

**Comment by cyang-kth** [comment]
I have not tried this function. Theoretically, you can try to download one big file from the official repo of OSM then use filtering tools (like osmfiltering) to get all highways. I am not sure if graph_from_xml will work on the filtered file or not. I think you need to post an issue on OSMNX to ask about it. As far as I remember, filtered file will lose some information and some tools will be unable to handle this format.

**Comment by Vedanta-Z** [comment]
@cyang-kth What if I use unfiltered data? Would fmm still work properly?

**Comment by cyang-kth** [comment]
Since you always need to use a shapefile as input, if you use unfiltered data you may use a lot of extra storage.

**Comment by michealowen** [comment]
I tried to use osmnx 1.0.1 , But the code has fiona error. 
D:\py_workspace\traffic_flow\road_network\CanYang\test.py:25: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  gdf_nodes.to_file(filepath_nodes, encoding=encoding)
Traceback (most recent call last):
  File "D:\py_workspace\traffic_flow\road_network\CanYang\test.py", line 36, in <module>
    save_graph_shapefile_directional(G, filepath='./network-new')
  File "D:\py_workspace\traffic_flow\road_network\CanYang\test.py", line 26, in save_graph_shapefile_directional
    gdf_edges.to_file(filepath_edges, encoding=encoding)
  File "D:\py_workspace\traffic_flow\lib\site-packages\geopandas\geodataframe.py", line 1086, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "D:\py_workspace\traffic_flow\lib\site-packages\geopandas\io\file.py", line 330, in _to_file
    colxn.writerecords(df.iterfeatures())
  File "D:\py_workspace\traffic_flow\lib\site-packages\fiona\collection.py", line 361, in writerecords
    self.session.writerecs(records, self)
  File "fiona\ogrext.pyx", line 1291, in fiona.ogrext.WritingSession.writerecs
  File "fiona\ogrext.pyx", line 466, in fiona.ogrext.OGRFeatureBuilder.build
ValueError: Invalid field type <class 'tuple'>

**Comment by cyang-kth** [comment]
It seems that you need to use an old version of osmnx according to previous comment. 

https://github.com/cyang-kth/osm_mapmatching/issues/13#issuecomment-769155502

**Comment by michealowen** [comment]
> It seems that you need to use an old version of osmnx according to previous comment.
> 
> [#13 (comment)](https://github.com/cyang-kth/osm_mapmatching/issues/13#issuecomment-769155502)

Thanks, I changed the OSMNX version to 0.15.0 and code run sucessfully. But when i use the program ubodt_gen.exe to generate ubodt.txt , an error occured 'Id, source, or target colmn not found'. How can I deal with it?

**Comment by cyang-kth** [comment]
You need to specify the id source and target column of that network file. You need to install the latest version that will print out the field which is not found by the program.

**Comment by michealowen** [comment]
> You need to specify the id source and target column of that network file. You need to install the latest version that will print out the field which is not found by the program.

Thanks for your reply, now I know why the ubodt_gen.exe doesn't work. But I think you'd better update the command line program in https://fmm-wiki.github.io/. Some developers who are new to the repo may have the same problem running the command line in https://fmm-wiki.github.io/.
