### ISSUE TITLE
example does not run to download shapefile from OSM

### ISSUE THREAD

**Issue by rvxfahim** [cyang-kth/osm_mapmatching#16]
![Screenshot from 2021-09-19 03-30-42](https://user-images.githubusercontent.com/32749520/133909044-8047399b-16e1-41fc-b560-6e28467499ad.png)
[osmnx_proj.zip](https://github.com/cyang-kth/osm_mapmatching/files/7190661/osmnx_proj.zip)

I get this error in terminal when I run the python script (inside zip file) given in https://github.com/cyang-kth/osm_mapmatching
Nothing changed, just copy pasted to check if everything runs properly.

**Comment by cyang-kth** [comment]
It seems to be that newer version of OSMNX generate Geodataframe in different format

```python
gdf_edges["fid"] = gdf_edges.index
```

```python
import numpy as np
gdf_edges["fid"] = np.arange(0, gdf_edges.shape[0], dtype='int')
```

**Comment by rvxfahim** [comment]
> It seems to be that newer version of OSMNX generate Geodataframe in different format
> 
> ```python
> gdf_edges["fid"] = gdf_edges.index
> ```
> 
> ```python
> import numpy as np
> gdf_edges["fid"] = np.arange(0, gdf_edges.shape[0], dtype='int')
> ```

this worked, thanks

**Comment by KrasnovPavel** [comment]
Can you, please, update readme?

**Comment by cyang-kth** [comment]
@KrasnovPavel 
Thanks for your suggestion. It has been updated now.
