### ISSUE TITLE
REVISED TITLE: ubodt.bin file extremely large

### ISSUE THREAD

**Issue by august-zhu** [cyang-kth/osm_mapmatching#3]
Hi,

I tried to test the web demo. After I build the ubodt.bin file, I failed running the python script fmm_web_app.py. And here is my error message:

```
Start reading FMM configuration
Finish with reading FMM configuration
------------------------------------------
Configuration parameters for map matching application:
 Network_file: college_park_dual.shp
Network id: id
Network source: source
Network target: target
ubodt_file: output/ubodt.bin
delta: undefined, to be inferred from ubodt file
ubodt format(1 binary, 0 csv): 1
k: 10
radius: 0.01
gps_error: 0.5
------------------------------------------
Loading model from filedata/college_park/fmm_web_config.xml
[2020-03-24 15:24:16.560] [info] [network.hpp:74] Read network from file college_park_dual.shp
[2020-03-24 15:24:16.570] [critical] [network.hpp:80] Open dataset failed.
```
Any suggestions?

Thanks!

**Comment by august-zhu** [comment]
Sorry, I may mess up with the web_config.xml file. Solved.

**Comment by august-zhu** [comment]
But I had another problem. My study area is much bigger than the city level, which has about 325,000 (with 135,000 nodes). I had the ubodt.bin file extremely large. Do you have any suggestions?

**Comment by cyang-kth** [comment]
@august-zhu 

I have posted an issue as a feature request on the original fmm repo

https://github.com/cyang-kth/fmm/issues/52

The solution is to avoid precomputing the table and directly performing routing queries such as the STMATCH algorithm described below 

Lou, Yin, et al. "Map-matching for low-sampling-rate GPS trajectories." Proceedings of the 17th ACM SIGSPATIAL international conference on advances in geographic information systems. 2009.

I have implemented a preliminary version of stmatch in that framework but it takes time to clean the code and update the repo.

**Comment by august-zhu** [comment]
@cyang-kth 

Thanks!

**Comment by cyang-kth** [comment]
@august-zhu 

The stmatch algorithm has been added to the fmm repo now, which does not need the precomputation. A new program called `stmatch` is generated in the repo. You are also welcome to try the web demo app.

**Comment by august-zhu** [comment]
@cyang-kth 

Thank you. I'll try it.
