### ISSUE TITLE
One question about pre-processing

### ISSUE THREAD

**Issue by michealowen** [cyang-kth/osm_mapmatching#4]
Hi,thank u for providing such a powerful application.
I have a question about the pre-processing. I have read the OSM XML downloaded by the python package-OSMNX in detail. I find that the edge which is not one-way is duplicate itself ,so I think duplicating the bidirectional edges is not necessary.

**Comment by cyang-kth** [comment]
@michealowen 

Thank you for pointing out this issue. Do you have the reference to this function? I am not sure if this feature is supported from a specific version of OSMNX or not.

**Comment by michealowen** [comment]
> @michealowen
> 
> Thank you for pointing out this issue. Do you have the reference to this function? I am not sure if this feature is supported from a specific version of OSMNX or not.

The version of OSMNX in my python virtual environment is 0.11.4. I use the founctions named graph_from_place() and save_graphml() to download and save the road data. And then I read the the XML ,I found this. (the attribute named d10 means the edge is one-way or not.False when the edge is not one-way. )

`<edge source="7086866443" target="7086866439" id="0">
  <data key="d8">758793289</data>
  <data key="d13">unclassified</data>
  <data key="d10">False</data>
  <data key="d14">68.899</data>
  <data key="d15">LINESTRING (113.3073959 34.6667786, 113.3075005 34.6669408, 113.3075997 34.6670478, 113.307762 34.6672044, 113.3078322 34.6672807)</data>
</edge>  `

`<edge source="7086866439" target="7086866443" id="0">
  <data key="d8">758793289</data>
  <data key="d13">unclassified</data>
  <data key="d10">False</data>
  <data key="d14">68.899</data>
  <data key="d15">LINESTRING (113.3078322 34.6672807, 113.307762 34.6672044, 113.3075997 34.6670478, 113.3075005 34.6669408, 113.3073959 34.6667786)</data>
</edge>`

the two edges above have opposite source node & target  node. On the contrary , the one-way edge  do not has a related edge which has opposite source node & target node.

**Comment by michealowen** [comment]
> @michealowen
> 
> Thank you for pointing out this issue. Do you have the reference to this function? I am not sure if this feature is supported from a specific version of OSMNX or not.

> @michealowen
> 
> Thank you for pointing out this issue. Do you have the reference to this function? I am not sure if this feature is supported from a specific version of OSMNX or not.

The version of OSMNX in my python virtual environment is 0.11.4. I use the founctions named graph_from_place() and save_graphml() to download and save the road data. And then I read the the XML ,I found this. (the attribute named d10 means the edge is one-way or not.False when the edge is not one-way. )

`<edge source="7086866443" target="7086866439" id="0">
  <data key="d8">758793289</data>
  <data key="d13">unclassified</data>
  <data key="d10">False</data>
  <data key="d14">68.899</data>
  <data key="d15">LINESTRING (113.3073959 34.6667786, 113.3075005 34.6669408, 113.3075997 34.6670478, 113.307762 34.6672044, 113.3078322 34.6672807)</data>
</edge>  `

`<edge source="7086866439" target="7086866443" id="0">
  <data key="d8">758793289</data>
  <data key="d13">unclassified</data>
  <data key="d10">False</data>
  <data key="d14">68.899</data>
  <data key="d15">LINESTRING (113.3078322 34.6672807, 113.307762 34.6672044, 113.3075997 34.6670478, 113.3075005 34.6669408, 113.3073959 34.6667786)</data>
</edge>`

the two edges above have opposite source node & target  node. On the contrary , the one-way edge  do not has a related edge which has opposite source node & target node.

**Comment by michealowen** [comment]
> @michealowen
> 
> Thank you for pointing out this issue. Do you have the reference to this function? I am not sure if this feature is supported from a specific version of OSMNX or not.

The version of OSMNX in my python virtual environment is 0.11.4. I use the founctions named graph_from_place() and save_graphml() to download and save the road data. And then I read the the XML ,I found this. (the attribute named d10 means the edge is one-way or not.False when the edge is not one-way. )

`<edge source="7086866443" target="7086866439" id="0">
  <data key="d8">758793289</data>
  <data key="d13">unclassified</data>
  <data key="d10">False</data>
  <data key="d14">68.899</data>
  <data key="d15">LINESTRING (113.3073959 34.6667786, 113.3075005 34.6669408, 113.3075997 34.6670478, 113.307762 34.6672044, 113.3078322 34.6672807)</data>
</edge>  `

`<edge source="7086866439" target="7086866443" id="0">
  <data key="d8">758793289</data>
  <data key="d13">unclassified</data>
  <data key="d10">False</data>
  <data key="d14">68.899</data>
  <data key="d15">LINESTRING (113.3078322 34.6672807, 113.307762 34.6672044, 113.3075997 34.6670478, 113.3075005 34.6669408, 113.3073959 34.6667786)</data>
</edge>`

the two edges above have opposite source node & target  node. On the contrary , the one-way edge  do not has a related edge which has opposite source node & target node.

**Comment by cyang-kth** [comment]
@michealowen 

I found from the official source code of osmnx that `save_graph_shapefile` seems to be different from `save_graphml`. When saving as shapefile, it contains an extra step to get undirected copy. I am not sure if it is the reason why the shapefile may not contain that the reversed edge. 

https://github.com/gboeing/osmnx/blob/15eddc0672f0ec951ada1b89eb417df44d35636e/osmnx/save_load.py#L93

```python
    start_time = time.time()
    if folder is None:
        folder = settings.data_folder

    # convert directed graph G to an undirected graph for saving as a shapefile
    G_save = get_undirected(G.copy())

    # create a GeoDataFrame of the nodes and set CRS
    nodes, data = zip(*G_save.nodes(data=True))
    gdf_nodes = gpd.GeoDataFrame(list(data), index=nodes)
    gdf_nodes.crs = G_save.graph['crs']
```

**Comment by michealowen** [comment]
> @michealowen
> 
> I found from the official source code of osmnx that `save_graph_shapefile` seems to be different from `save_graphml`. When saving as shapefile, it contains an extra step to get undirected copy. I am not sure if it is the reason why the shapefile may not contain that the reversed edge.
> 
> https://github.com/gboeing/osmnx/blob/15eddc0672f0ec951ada1b89eb417df44d35636e/osmnx/save_load.py#L93
> 
> ```python
>     start_time = time.time()
>     if folder is None:
>         folder = settings.data_folder
> 
>     # convert directed graph G to an undirected graph for saving as a shapefile
>     G_save = get_undirected(G.copy())
> 
>     # create a GeoDataFrame of the nodes and set CRS
>     nodes, data = zip(*G_save.nodes(data=True))
>     gdf_nodes = gpd.GeoDataFrame(list(data), index=nodes)
>     gdf_nodes.crs = G_save.graph['crs']
> ```

Oaky，

**Comment by michealowen** [comment]
> @michealowen
> 
> I found from the official source code of osmnx that `save_graph_shapefile` seems to be different from `save_graphml`. When saving as shapefile, it contains an extra step to get undirected copy. I am not sure if it is the reason why the shapefile may not contain that the reversed edge.
> 
> https://github.com/gboeing/osmnx/blob/15eddc0672f0ec951ada1b89eb417df44d35636e/osmnx/save_load.py#L93
> 
> ```python
>     start_time = time.time()
>     if folder is None:
>         folder = settings.data_folder
> 
>     # convert directed graph G to an undirected graph for saving as a shapefile
>     G_save = get_undirected(G.copy())
> 
>     # create a GeoDataFrame of the nodes and set CRS
>     nodes, data = zip(*G_save.nodes(data=True))
>     gdf_nodes = gpd.GeoDataFrame(list(data), index=nodes)
>     gdf_nodes.crs = G_save.graph['crs']
> ```

If i use the function "save_graphml" , i do not need to duplicate the bidirectional edges right?
And I have another question , can I just run the code in fmm/python/ on Windows(python 3.7)? I read the README.md  and  I noticed that you are testing your code on Ubuntu. I will try it on Windows ,maybe many problems are waiting for me.

**Comment by cyang-kth** [comment]
@michealowen 

I think the road network needs to be stored in Shapefile in order to use FMM. 
It would be much easier if you are running it on Ubuntu. 

For windows, I think you need to install cygwin in order to use it. 
https://fmm-wiki.github.io/docs/installation/windows.html

I am using the python 2.7 I am not sure if it also works on 3.7.

**Comment by michealowen** [comment]
> @michealowen
> 
> I think the road network needs to be stored in Shapefile in order to use FMM.
> It would be much easier if you are running it on Ubuntu.
> 
> For windows, I think you need to install cygwin in order to use it.
> https://fmm-wiki.github.io/docs/installation/windows.html
> 
> I am using the python 2.7 I am not sure if it also works on 3.7.

Thanks a lot! I will try it.

**Comment by michealowen** [comment]
> @michealowen
> 
> I think the road network needs to be stored in Shapefile in order to use FMM.
> It would be much easier if you are running it on Ubuntu.
> 
> For windows, I think you need to install cygwin in order to use it.
> https://fmm-wiki.github.io/docs/installation/windows.html
> 
> I am using the python 2.7 I am not sure if it also works on 3.7.

I have followed the instructions on https://fmm-wiki.github.io/docs/installation/windows.html. But finally when i run the fmm_test.py to verify the installation, an error occured. It shows 
"ImportError: No module named fmm". Only in the /python/build folder can i successfully import fmm

**Comment by michealowen** [comment]
> @michealowen
> 
> I think the road network needs to be stored in Shapefile in order to use FMM.
> It would be much easier if you are running it on Ubuntu.
> 
> For windows, I think you need to install cygwin in order to use it.
> https://fmm-wiki.github.io/docs/installation/windows.html
> 
> I am using the python 2.7 I am not sure if it also works on 3.7.

I have followed the instructions on https://fmm-wiki.github.io/docs/installation/windows.html. But finally when i run the fmm_test.py to verify the installation, an error occured. It shows
"ImportError: No module named fmm". Only in the /python/build folder can i successfully import fmm.

**Comment by cyang-kth** [comment]
@michealowen 

Sorry about that problem. I think the installation of windows system misses one step, which is step 2 in the link below

https://fmm-wiki.github.io/docs/installation/ubuntu.html#install-python-extension

Add the build folder to the environment variable PYTHONPATH (set the PATH_TO_BUILD_FOLDER below to the absolute path of the build folder, e.g., /home/Administrator/workspace/fmm/python/build, you can run pwd to check the absolute path of the current folder):

```
 echo 'export PYTHONPATH=${PYTHONPATH}:PATH_TO_BUILD_FOLDER' >> ~/.bashrc
 source ~/.bashrc
```

Once you add the build folder to PYTHONPATH. You can import it from other places.

**Comment by cyang-kth** [comment]
I have also updated the documentation to add this step. Sorry about that.

**Comment by michealowen** [comment]
> I have also updated the documentation to add this step. Sorry about that.

Never mind. Thank you for helping me a lot.  I can sucessfully import fmm now.Thank you very much!
The article link https://www.tandfonline.com/doi/full/10.1080/13658816.2017.1400548 on fmm README.md needed to pay for it. Any other ways to fetch it? Thanks a lot.

**Comment by cyang-kth** [comment]
@michealowen 

A post print version is at my home page 

https://people.kth.se/~cyang/bib/fmm.pdf

**Comment by michealowen** [comment]
> @michealowen
> 
> A post print version is at my home page
> 
> https://people.kth.se/~cyang/bib/fmm.pdf

got it!! Thank you!
