### ISSUE TITLE
A question about pgsql2shp

### ISSUE THREAD

**Issue by michealowen** [cyang-kth/osm_mapmatching#5]
Hi,sorry to bother you again.
When i tried to export the dual data to shp using pgsql2shp command, an error occured. It shows "
WARNING: Cannot determine spatial reference (empty table or unknown spatial ref). No prj file will be generated. ".
I think it may caused by the srid. When I import the shp data, we donot determine the spatial reference, such as Mercator. 
Thanks a lot.

**Comment by cyang-kth** [comment]
@michealowen 

As long as you are using the data from OSM, the default SRID is 4326 and the units are latitude and longitude. It is fine to run the map matching in the precondition that the network is also in unit of degrees. You need to be careful about the spatial unit of GPS error and search radius configuration, which will also be in unit of degree. 

If you want to match GPS data with 50 meter GPS error and search radius of 300 meter, the gps error configuration will be set 0.0005 and search radius set as 0.003. (the unit will be the same as GPS data and network data).

**Comment by michealowen** [comment]
Thanks a lot, now I can correctly export the table to shp.
